export const techIcons: Record<string, string> = {
  'Aseprite':      '/icons/tech/aseprite.png',
  'Next.js':       '/icons/tech/nextjs.png',
  'React':         '/icons/tech/react.png',
  'TypeScript':    '/icons/tech/typescript.png',
  'Python':        '/icons/tech/python.png',
  'Flask':         '/icons/tech/flask.png',
  'Supabase':      '/icons/tech/supabase.png',
  'Node.js':       '/icons/tech/node.png',
  'CSS':           '/icons/tech/css.png',
  'Git':           '/icons/tech/git.png',
  'PowerBI':       '/icons/tech/powerbi.png',
  'JavaScript':    '/icons/tech/javascript.png',
  'Make':          '/icons/tech/make.png',
  'Activepieces':  '/icons/tech/activepieces.png',
  'Gemini':        '/icons/tech/gemini.png',
}

export const techCategories: Record<string, 'Frontend' | 'Backend' | 'Tools' | 'Automatización'> = {
  'Next.js':       'Frontend',
  'React':         'Frontend',
  'TypeScript':    'Frontend',
  'JavaScript':    'Frontend',
  'CSS':           'Frontend',
  'Python':        'Backend',
  'Flask':         'Backend',
  'Supabase':      'Backend',
  'Node.js':       'Backend',
  'Git':           'Tools',
  'Aseprite':      'Tools',
  'PowerBI':       'Tools',
  'Make':          'Automatización',
  'Activepieces':  'Automatización',
  'Gemini':        'Automatización',
}